- name: Deploy MAC Desktop with Ansible
  hosts: desktop
  become: false
  tasks:
      - name: "Install Homebrew Packages"
        homebrew:
          name: "{{ packages }}"
        vars:
          packages:
            - 'autoconf'
            - 'azure-cli'
            - 'bash-completion'
            - 'bash-completion'
            - 'boot2docker'
            - 'ccze'
            - 'consul'
            - 'coreutils'
            - 'curl'
            - 'derailed/k9s/k9s'
            - 'docker-compose'
            - 'docker-machine'
            - 'doxygen'
            - 'freerdp'
            - 'gcc'
            - 'git'
            - 'git-flow'
            - 'git-ftp'
            - 'git-lfs'
            - 'go'
            - 'htop'
            - 'hub'
            - 'imagemagick'
            - 'jq'
            - 'kubectl'
            - 'kubernetes-helm'
            - 'libmagic'
            - 'libyaml'
            - 'minikube'
            - 'nano'
            - 'ncdu'
            - 'nmap'
            - 'node'
            - 'nomad'
            - 'openfortivpn'
            - 'openssl'
            - 'packer'
            # - 'powerlevel9k'
            - 'pyenv'
            - 'python'
            - 'rancher-compose'
            - 'rbenv'
            - 'rcm'
            - 'rdesktop'
            - 'readline'
            - 'reattach-to-user-namespace'
            - 'ruby-build'
            - 'sambadevi/powerlevel9k/powerlevel9k'
            - 'ssh-copy-id'
            - 'syncthing'
            - 'terraform'
            - 'terraform-inventory'
            - 'terraform-provisioner-ansible'
            - 'the_silver_searcher'
            - 'tmux'
            - 'tree'
            - 'universal-ctags'
            - 'vault'
            - 'vim'
            - 'watch'
            - 'watchman'
            - 'wget'
            - 'xz'
            - 'yarn'
            - 'zsh'
            - 'zsh-syntax-highlighting'
          state: present
          update_homebrew: yes
          upgrade_all: yes
      
      - name: "Install Homebrew Cask Packages"
        homebrew_cask:
          name: "{{ packages }}"
        vars:
          packages:
            - 'android-platform-tools'
            - 'android-studio'
            - 'atom'
            - 'azure-data-studio'
            - 'discord'
            - 'docker'
            - 'dropbox'
            - 'firefox'
            - 'forticlient'
            - 'font-hack-nerd-font'
            - 'gimp'
            - 'google-chrome'
            - 'google-cloud-sdk'
            # - 'google-drive'
            - 'google-hangouts'
            - 'gpg-suite'
            - 'ibm-cloud-cli'
            - 'insomnia'
            - 'intellij-idea-ce'
            - 'iterm2'
            - 'java'
            - 'keepassxc'
            - 'lastpass'
            - 'libreoffice'
            - 'macvim'
            - 'meld'
            - 'microsoft-teams'
            - 'mysqlworkbench'
            # - 'nmap'
            - 'pgadmin4'
            - 'postman'
            - 'robo-3t'
            - 'royal-tsx'
            - 'signal'
            - 'skype'
            - 'slack'
            # - 'sling'
            - 'soapui'
            - 'spotify'
            - 'sublime-text'
            # - 'teamviewer'
            - 'telegram'
            - 'tor-browser'
            - 'vagrant'
            - 'vagrant-manager'
            # - 'virtualbox'
            # - 'virtualbox-extension-pack'
            - 'visual-studio-code'
            - 'vlc'
            - 'wine-stable'
            # - 'xquartz'
            - 'zoom'
          state: present
          update_homebrew: yes
          upgrade_all: yes
