- name: Deploy MAC Machine with Ansible
  hosts: macos
  become: false
  tasks:
      - name: "Install Homebrew Packages"
        community.general.homebrew:
          name: "{{ packages }}"
        vars:
          packages:
            # - 'azure-cli'
            # - 'consul'
            # - 'derailed/k9s/k9s'
            # - 'freerdp'
            # - 'minikube'
            # - 'nomad'
            # - 'openfortivpn'
            # - 'rancher-compose'
            # - 'rdesktop'
            # - 'syncthing'
            - 'autoconf'
            - 'bash-completion'
            - 'boot2docker'
            # - 'ccze'
            - 'coreutils'
            - 'cowsay'
            - 'curl'
            - 'docker-compose'
            - 'docker-machine'
            - 'doxygen'
            - 'gcc'
            - 'gettext'
            - 'gifsicle'
            - 'git'
            - 'git-flow'
            - 'git-ftp'
            - 'git-lfs'
            - 'github/gh/gh'
            - 'go'
            - 'gpg'
            - 'htop'
            - 'httpie'
            - 'hub'
            - 'hudochenkov/sshpass/sshpass'
            - 'imagemagick'
            - 'iperf'
            - 'jq'
            - 'kubectl'
            - 'kubernetes-helm'
            - 'libevent'
            - 'libmagic'
            - 'libyaml'
            - 'mcrypt'
            - 'nano'
            - 'ncdu'
            - 'nmap'
            - 'node'
            - 'nvm'
            - 'openssl'
            - 'packer'
            - 'php'
            - 'pv'
            - 'pyenv'
            - 'python'
            - 'rbenv'
            - 'rcm'
            - 'readline'
            - 'reattach-to-user-namespace'
            - 'ruby-build'
            - 'sambadevi/powerlevel9k/powerlevel9k'
            - 'sqlite'
            - 'ssh-copy-id'
            - 'terraform'
            - 'terraform-inventory'
            - 'the_silver_searcher'
            - 'tmux'
            - 'tree'
            - 'universal-ctags'
            - 'vault'
            - 'vim'
            - 'watch'
            - 'watchman'
            - 'wget'
            - 'wrk'
            - 'xz'
            - 'yarn'
            - 'zsh'
            - 'zsh-syntax-highlighting'
          state: present
          update_homebrew: yes
          upgrade_all: yes
          
      - name: "Install Homebrew TAP Packages"
        community.general.homebrew_tap:
          name: "{{ packages }}"
        vars:
          packages:
            - 'homebrew/cask'
            - 'homebrew/cask-versions'
            - 'homebrew/core'
            # - 'caskroom/cask'
          state: present

      - name: "Install Homebrew Cask Packages"
        community.general.homebrew_cask:
          name: "{{ packages }}"
        vars:
          packages:
            # - 'atom'
            # - 'azure-data-studio'
            # - 'discord'
            # - 'dropbox'
            # - 'forticlient'
            # - 'gimp'
            # - 'google-drive'
            # - 'google-hangouts'
            # - 'ibm-cloud-cli'
            # - 'intellij-idea-ce'
            # - 'keepassxc'
            # - 'lastpass'
            # - 'libreoffice'
            # - 'microsoft-teams'
            # - 'mysqlworkbench'
            # - 'nmap'
            # - 'pgadmin4'
            # - 'robo-3t'
            # - 'signal'
            # - 'skype'
            # - 'slack'
            # - 'sling'
            # - 'soapui'
            # - 'spotify'
            # - 'sublime-text'
            # - 'teamviewer'
            # - 'telegram'
            # - 'tor-browser'
            # - 'virtualbox'
            # - 'virtualbox-extension-pack'
            # - 'visual-studio-code'
            # - 'vlc'
            # - 'zoom'
            - 'android-platform-tools'
            - 'android-studio'
            - 'chromedriver'
            - 'docker'
            - 'firefox'
            - 'font-hack-nerd-font'
            - 'google-chrome'
            - 'google-cloud-sdk'
            - 'gpg-suite'
            - 'insomnia'
            - 'iterm2'
            - 'java'
            - 'macvim'
            - 'meld'
            - 'postman'
            - 'royal-tsx'
            - 'vagrant'
            - 'vagrant-manager'
            - 'wine-stable'
            - 'xquartz'
          state: present
          upgrade_all: yes
          update_homebrew: yes
          # install_options: force

# Aditional Tasks
