- name: Deploy MAC Machine with Ansible
  hosts: macos
  become: false

  vars:
    sudoers:
      - admin
      - administrator
    ohmyzsh_folders:
      - "/usr/local/share/zsh"
      - "/usr/local/share/zsh/site-functions"

  roles:
    - common-mac
    - gitlab-runner

  tasks:
